// Typed API client hitting the FastAPI backend. In dev, requests go to "/api"
// which Vite proxies to http://localhost:8000. If a request fails (backend
// down, network error, non-2xx), we transparently fall back to mock data so
// every page still renders. Each response is tagged so the UI can show a
// "mock" badge.
import type {
  ArchitectureView,
  AskCompareResponse,
  AskRequest,
  Capabilities,
  ChatRequest,
  ChatResponse,
  CompareResult,
  EvaluationReport,
  HealthInfo,
  HeadlineMetrics,
  LabInfo,
  PipelineView,
  RunCreate,
  RunDetail,
  RunSummary,
  SystemDesign,
} from "./types";
import {
  mockCapabilities,
  mockChat,
  mockEvaluation,
  mockHealth,
  mockOverview,
  mockPipeline,
  mockSystem,
} from "./mock";

// Base URL: "/api" in dev (proxied). Override with VITE_API_BASE if needed.
const BASE = (import.meta.env.VITE_API_BASE as string | undefined) ?? "/api";

export interface Sourced<T> {
  data: T;
  isMock: boolean;
  error?: string;
}

// Throws with the backend's `detail` message when it sends one (FastAPI errors).
async function failure(path: string, res: Response): Promise<Error> {
  try {
    const body = await res.json();
    if (typeof body?.detail === "string") return new Error(body.detail);
  } catch {
    /* non-JSON error body */
  }
  return new Error(`${path} -> HTTP ${res.status}`);
}

async function getJson<T>(path: string): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    headers: { Accept: "application/json" },
  });
  if (!res.ok) throw await failure(path, res);
  return (await res.json()) as T;
}

async function postJson<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw await failure(path, res);
  return (await res.json()) as T;
}

async function withFallback<T>(
  fn: () => Promise<T>,
  fallback: T
): Promise<Sourced<T>> {
  try {
    const data = await fn();
    return { data, isMock: false };
  } catch (e) {
    return {
      data: fallback,
      isMock: true,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

export const api = {
  health: () => withFallback<HealthInfo>(() => getJson("/health"), mockHealth),
  capabilities: () =>
    withFallback<Capabilities>(() => getJson("/capabilities"), mockCapabilities),
  overview: () =>
    withFallback<HeadlineMetrics>(() => getJson("/overview"), mockOverview),
  pipeline: () =>
    withFallback<PipelineView>(() => getJson("/pipeline"), mockPipeline),
  evaluation: () =>
    withFallback<EvaluationReport>(() => getJson("/evaluation"), mockEvaluation),
  system: () => withFallback<SystemDesign>(() => getJson("/system"), mockSystem),
  chat: (req: ChatRequest) =>
    withFallback<ChatResponse>(() => postJson("/chat", req), {
      ...mockChat,
      question: req.question || mockChat.question,
    }),
};

// Experiment lab: no mock fallback - runs are real or they are an error.
export const lab = {
  info: () => getJson<LabInfo>("/lab/info"),
  createRun: (req: RunCreate) => postJson<RunSummary>("/runs", req),
  runs: () => getJson<RunSummary[]>("/runs"),
  run: (id: string) => getJson<RunDetail>(`/runs/${encodeURIComponent(id)}`),
  compare: (a: string, b: string) =>
    getJson<CompareResult>(`/runs/compare?a=${encodeURIComponent(a)}&b=${encodeURIComponent(b)}`),
};

// Ask: compare combinations for one question, then answer once. No mock fallback.
export const ask = {
  compare: (req: AskRequest) => postJson<AskCompareResponse>("/ask/compare", req),
  answer: (req: AskRequest) => postJson<ChatResponse>("/ask/answer", req),
};

// Architecture diagrams, generated by the backend from live constants and build status.
export const architecture = () => getJson<ArchitectureView>("/architecture");
